[workspace]
members = [
	"i73-frontend",
	"i73-image",
	"i73-noise",
	"i73-biome",
	"i73-shape",
	"i73-trig",
	"i73-base",
	"i73-terrain",
	"i73-structure",
	"i73-decorator"
]

[profile.dev]
opt-level = 3

[profile.release]
lto = true
