[package]
name = "i73-structure"
version = "0.1.0"
authors = ["coderbot <coderbot16@gmail.com>"]

[dependencies]
java-rand = "0.2.0"
vocs = { path = "../../vocs" }
i73-base = { path = "../i73-base" }
i73-trig = { path = "../i73-trig" }