[package]
name = "biome"
version = "0.1.0"
authors = ["coderbot <coderbot16@gmail.com>"]

[dependencies]
cgmath = "0.16"
java-rand = "0.2.0"
serde = "0.9"
serde_derive = "0.9"
vocs = { path = "../../vocs" }
noise = { path = "../noise" }