[package]
name = "vocs"
version = "0.1.0"
authors = ["coderbot16 <coderbot16@gmail.com>"]
edition = "2018"

[dependencies]
bit-vec = "0.6"
fxhash = "0.2.1"
splitmut = "0.2.1"

[dependencies.spin]
version = "0.4"
default-features = false
