[package]
name = "classicworld"
version = "0.1.0"
authors = ["coderbot <coderbot16@gmail.com>"]
edition = "2018"

[dependencies]
vocs = { path = "../../vocs" }
nbt-turbo = { path = "../../nbt-turbo" }
deflate = "0.8"
